name: CI
on:
  push:
    branches: [ main ]
jobs:
  build-package:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Set Node.js 23.x
        uses: actions/setup-node@v4
        with:
          node-version: 23.x
      - name: enable corepack
        run: corepack enable
      - run: |
          apt-get update
          pip install pyodide-build
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          PYODIDE_EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version)
          ./emsdk install ${PYODIDE_EMSCRIPTEN_VERSION}
          ./emsdk activate ${PYODIDE_EMSCRIPTEN_VERSION}
          source emsdk_env.sh
          cd ..
          pyodide build --outdir web/src/public/assets/
        shell: bash
      - name: cachebustfix
        run: |
          mv web/src/public/assets/webhorus-0.1.0-cp312-cp312-pyodide_2024_0_wasm32.whl web/src/public/assets/webhorus-0.1.0-cp312-cp312-pyodide_2024_0_wasm32_1.whl
      - name: Yarn
        run: |
          cd web
          yarn install
          yarn build
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: webhorus.whl
          path: web/src/public/assets/webhorus-*.whl
      - name: 'Upload Web Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: web/src/dist/**
  deploy:
    needs: build-package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Download web
        uses: actions/download-artifact@v4
        with:
          name: web
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::143841941773:role/github
      - run: |
          aws s3 sync . s3://horus.sondehub.org/ --delete
          aws s3 cp --content-type application/wasm ./assets/pyodide.asm.wasm s3://horus.sondehub.org/assets/pyodide.asm.wasm
          aws cloudfront create-invalidation --distribution-id EGCXXLSXJCNP5  --paths '/*'
