name: CI
on:
  push:
    branches: [ main ]
jobs:
  build-package:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - run: |
          apt-get update
          pip install pyodide-build
          git clone https://github.com/emscripten-core/emsdk.git
          cd emsdk
          PYODIDE_EMSCRIPTEN_VERSION=$(pyodide config get emscripten_version)
          ./emsdk install ${PYODIDE_EMSCRIPTEN_VERSION}
          ./emsdk activate ${PYODIDE_EMSCRIPTEN_VERSION}
          source emsdk_env.sh
          cd ..
          pyodide build --outdir web/
        shell: bash
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: webhorus.whl
          path: web/*.whl